In [1]:
# Array Attributes using Numpy

import numpy as np
a=np.array([[1,2,3],[4,5,6]])

#shape of the array (row,coloumn)
print("The Shape of the Array a\n",a.shape)

#Resize the shape
a.shape=(3,2)
print ("After the resize the shape\n",a)

#NumPy also provides a reshape function to resize an array.
a=a.reshape(3,2)
print("Using resshape in NUmpy for Array a\n",a)

#ndarray.ndim
#This array attribute returns the number of array dimensions

a=np.arange(24)  # an array of evenly spaced numbers 
print("Print this array in a sequence\n",a)

a.ndim
a=a.reshape(3,4,2)
print ("After using ndim this array is reshaped (number of matrix, row, coloumn)\n",a)

The Shape of the Array a
 (2, 3)
After the resize the shape
 [[1 2]
 [3 4]
 [5 6]]
Using resshape in NUmpy for Array a
 [[1 2]
 [3 4]
 [5 6]]
Print this array in a sequence
 [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]
After using ndim this array is reshaped (number of matrix, row, coloumn)
 [[[ 0  1]
  [ 2  3]
  [ 4  5]
  [ 6  7]]

 [[ 8  9]
  [10 11]
  [12 13]
  [14 15]]

 [[16 17]
  [18 19]
  [20 21]
  [22 23]]]
