In [1]:
#Matrix Operation using array

import numpy as np
a=np.array([[1,2,3],[4,5,6]])
print(a)

b=np.array([[1,2,3],[4,5,6]])

c=a+b #adding two matrices
print("Addition Operation of Matrix\n",c)

d=np.array([[1,2],[3,4],[5,6]])
mul=a.dot(d)
print("Multiplication operation in matrix\n",mul)

print("Transprose matrix\n",d.transpose())

print("Inverse Matrix\n",np.linalg.inv(mul) )

#accessing matrix

print(c[0][1])
print(c[1][1])


#Accessing row

print(c[1])

#Accessing Coloumn
print(c[:,2])

[[1 2 3]
 [4 5 6]]
Addition Operation of Matrix
 [[ 2  4  6]
 [ 8 10 12]]
Multiplication operation in matrix
 [[22 28]
 [49 64]]
Transprose matrix
 [[1 3 5]
 [2 4 6]]
Inverse Matrix
 [[ 1.77777778 -0.77777778]
 [-1.36111111  0.61111111]]
4
10
[ 8 10 12]
[ 6 12]
